export const ARABIC = {
  common: {
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    add: 'إضافة',
    update: 'تحديث',
    confirm: 'تأكيد',
    back: 'رجوع',
    next: 'التالي',
    submit: 'إرسال',
    search: 'بحث',
    filter: 'تصفية',
    export: 'تصدير',
    import: 'استيراد',
    refresh: 'تحديث',
    loading: 'جاري التحميل...',
    saving: 'جاري الحفظ...',
    exporting: 'جاري التصدير...',
    success: 'تمت العملية بنجاح',
    error: 'حدث خطأ',
    required: 'هذا الحقل مطلوب',
    yes: 'نعم',
    no: 'لا',
    close: 'إغلاق',
    actions: 'الإجراءات',
    status: 'الحالة',
    createdAt: 'تاريخ الإنشاء',
    updatedAt: 'تاريخ التحديث',
    tryAgain: 'حاول مرة أخرى',
    clearAll: 'مسح الكل',
    warning: 'تحذير',
    optional: 'اختياري',
    none: 'لا يوجد',
    confirmDelete: 'هل أنت متأكد من الحذف؟',
    selectCategory: 'اختر التصنيف',
    updateDetails: 'تحديث التفاصيل',
    createNew: 'إنشاء جديد',
    deactivate: 'تعطيل',
    activate: 'تفعيل',
    noPaymentMethods: 'لا توجد طرق دفع. أضف واحدة للبدء.',
    fixed: 'مبلغ ثابت',
  },

  nav: {
    dashboard: 'لوحة التحكم',
    pos: 'نقطة البيع',
    products: 'المنتجات',
    categories: 'التصنيفات',
    inventory: 'المخزون',
    partners: 'الشركاء',
    reports: 'التقارير',
    settings: 'الإعدادات',
    salesReport: 'تقرير المبيعات',
    partnersReport: 'تقرير الشركاء',
    inventoryReport: 'تقرير المخزون',
  },

  dashboard: {
    title: 'لوحة التحكم',
    subtitle: 'تحليلات الأعمال والتتبع بالوقت الفعلي',
    totalRevenue: 'إجمالي الإيرادات',
    partners: 'الشركاء',
    lowStockItems: 'المنتجات المنخفضة',
    salesGrowth: 'نمو المبيعات',
    partnerDividends: 'أرباح الشركاء',
    stockActivity: 'حركة المخزون',
    viewDetails: 'عرض التفاصيل',
    manage: 'إدارة',
    reports: 'التقارير',
    quickNavigation: 'التنقل السريع',
    salesPOS: 'نقطة البيع',
    salesPOSDesc: 'تشغيل الوحدة لإنشاء مبيعات جديدة ومعالجة الدفع.',
    inventory: 'المخزون',
    inventoryDesc: 'تعديل الكتالوجات وإضافة المنتجات وتتبع التصنيفات.',
    partnersDesc: 'أتمتة توزيع الأرباح وإدارة حصص المستثمرين.',
  },

  pos: {
    title: 'نقطة البيع',
    subtitle: 'معالجة عملية جديدة',
    product: 'المنتج',
    quantity: 'الكمية',
    price: 'السعر',
    total: 'الإجمالي',
    subtotal: 'المجموع الفرعي',
    fees: 'الرسوم',
    vat: 'ضريبة القيمة المضافة',
    grandTotal: 'الإجمالي الكلي',
    shipping: 'الشحن',
    installation: 'التركيب',
    custom: 'مخصص',
    paymentMethod: 'طريقة الدفع',
    selectPaymentMethod: 'اختر طريقة الدفع',
    completeSale: 'إتمام البيع',
    clearCart: 'إفراغ السلة',
    cartEmpty: 'السلة فارغة',
    addProducts: 'أضف منتجات للبدء',
    saleComplete: 'تمت عملية البيع بنجاح',
    saleHistory: 'سجل المبيعات',
    saleDetails: 'تفاصيل البيع',
    reversal: 'إلغاء',
    reversalReason: 'سبب الإلغاء',
    confirmReversal: 'تأكيد إلغاء البيع',
    saleCancelled: 'تم إلغاء البيع',
    receipt: 'إيصال',
    printReceipt: 'طباعة الإيصال',
    quickSelect: 'الاختيار السريع',
    clickToAdd: 'انقر على منتج لإضافته إلى السلة',
    currentCart: 'السلة الحالية',
    orderSummary: 'ملخص الطلب',
    note: 'ملاحظة',
    optional: 'اختياري',
    addRemark: 'أضف ملاحظة...',
    searchProducts: 'البحث عن منتجات...',
    each: 'للوحدة',
    financialBreakdown: 'تفصيل مالي',
    items: 'المنتجات',
    at: '@',
    totalFees: 'إجمالي الرسوم',
    additionalFees: 'رسوم إضافية',
    configurePresets: 'تكوين الإعدادات المسبقة في الإعدادات',
    fixed: 'ثابت',
    ofSubtotal: 'من المجموع الفرعي',
    feeType: 'نوع الرسوم',
    labelOptional: 'التسمية (اختياري)',
    expressExample: 'مثال: توصيل سريع',
    valueType: 'نوع القيمة',
    fixedAmount: 'مبلغ ثابت',
    percentage: 'نسبة مئوية',
    quickAmounts: 'مبالغ سريعة',
    amount: 'المبلغ',
    addFee: 'إضافة الرسوم',
    noPaymentMethods: 'لا توجد طرق دفع متاحة',
    confirmSaleMessage: 'هل أنت متأكد من إتمام هذا البيع؟ لا يمكن التراجع عن هذا الإجراء.',
    tryAdjustingFilters: 'جرب تعديل الفلاتر أو البحث',
    reverseSale: 'إلغاء البيع',
    reversalWarning: 'سيؤدي هذا إلى إلغاء البيع وإرجاع جميع العناصر إلى المخزون. لا يمكن التراجع عن هذا الإجراء.',
    enterReversalReason: 'أدخل سبب إلغاء هذا البيع...',
    warning: 'تحذير',
    saleNotFound: 'لم يتم العثور على البيع',
    noSales: 'لا توجد مبيعات',
    noSalesDesc: 'لم يتم تسجيل أي مبيعات بعد',
  },

  products: {
    title: 'إدارة المنتجات',
    subtitle: 'الكاش والفئات وتتبع المخزون',
    productName: 'اسم المنتج',
    sku: 'رمز المنتج',
    category: 'التصنيف',
    basePrice: 'السعر الأساسي',
    sellingPrice: 'سعر البيع',
    stockQuantity: 'الكمية المتاحة',
    status: 'الحالة',
    active: 'نشط',
    inactive: 'غير نشط',
    addProduct: 'إضافة منتج',
    editProduct: 'تعديل المنتج',
    deleteProduct: 'حذف المنتج',
    noProducts: 'لا توجد منتجات',
    addProductStart: 'أضف منتجاً جديداً للبدء',
    searchProducts: 'البحث عن منتجات...',
    filterByCategory: 'تصفية حسب التصنيف',
    allCategories: 'جميع التصنيفات',
    inStock: 'متوفر',
    outOfStock: 'نفذ',
    lowStock: 'مخزون منخفض',
  },

  categories: {
    title: 'إدارة التصنيفات',
    subtitle: 'تنظيم المنتجات في تصنيفات',
    categoryName: 'اسم التصنيف',
    categoryColor: 'لون التصنيف',
    productCount: 'عدد المنتجات',
    addCategory: 'إضافة تصنيف',
    editCategory: 'تعديل التصنيف',
    deleteCategory: 'حذف التصنيف',
    noCategories: 'لا توجد تصنيفات',
    addCategoryStart: 'أضف تصنيفاً جديداً للبدء',
  },

  inventory: {
    title: 'إدارة المخزون',
    subtitle: 'تتبع المنتجات منخفضة المخزون وتعديل الكميات',
    lowStockAlerts: 'تنبيهات المخزون المنخفض',
    inventoryLog: 'سجل المخزون',
    restock: 'إعادة التخزين',
    adjustment: 'تعديل الكمية',
    selectProduct: 'اختر المنتج',
    reason: 'السبب',
    quantity: 'الكمية',
    balance: 'الرصيد',
    delta: 'التغيير',
    movements: 'الحركات',
    movementsList: 'قائمة الحركات',
    movementTypes: {
      sale: 'مبيعة',
      restock: 'إعادة تخزين',
      adjustment: 'تعديل',
      reversal: 'إلغاء',
    },
    restockSuccess: 'تمت إعادة التخزين بنجاح',
    adjustmentSuccess: 'تم التعديل بنجاح',
    allStockHealthy: 'مستويات المخزون صحية',
    supplyRestock: 'إمداد إعادة التخزين',
    manualAdjustment: 'تعديل يدوي',
    damaged: 'تالف',
    returned: 'مرتجع',
    found: 'معثور',
    other: 'أخرى',
    left: 'متبقي',
    noLogEntries: 'لا توجد سجلات',
    clickProductToView: 'انقر على منتج لعرض سجل المخزون',
    submitRestock: 'إرسال إعادة التخزين',
    confirmAdjustment: 'تأكيد التعديل',
    enterReason: 'أدخل السبب',
    inStock: 'متوفر',
  },


  partners: {
    title: 'إدارة الشركاء',
    subtitle: 'تتبع حصص الشركاء وتوزيع الأرباح',
    partnerName: 'اسم الشريك',
    sharePercentage: 'نسبة الربح',
    investmentAmount: 'مبلغ الاستثمار',
    assignedProducts: 'المنتجات المسجلة',
    addPartner: 'إضافة شريك',
    editPartner: 'تعديل الشريك',
    deletePartner: 'حذف الشريك',
    noPartners: 'لا يوجد شركاء',
    addPartnerStart: 'أضف شريك استثماري للبدء في تتبع التوزيعات',
    distributeProfits: 'توزيع الأرباح',
    distributionSuccess: 'تم التوزيع بنجاح',
    totalDistributed: 'إجمالي الأرباح الموزعة',
    amountReceived: 'المبلغ المستلم',
    partnerNamePlaceholder: 'مثال: أحمد محمد',
    distributionNote: 'يتم إنشاء التوزيعات من الأرباح المحددة. يمكنك تصفية حسب نطاق التاريخ اختيارياً.',
    startDate: 'من تاريخ',
    endDate: 'إلى تاريخ',
    runDistribution: 'تشغيل التوزيع',
    viewHistory: 'عرض السجل',
    partnerHistory: 'سجل الشريك',
    partnerNotFound: 'الشريك غير موجود',
    distributionHistory: 'سجل التوزيعات',
    noDistributions: 'لا توجد توزيعات بعد',
    assignments: {
      title: 'تخصيصات المنتجات',
      subtitle: 'توزيع كميات محددة من المنتجات للشركاء',
      newAssignment: 'تخصيص جديد',
      editAssignment: 'تعديل التخصيص',
      deleteAssignment: 'حذف التخصيص',
      confirmDelete: 'هل أنت متأكد من حذف هذا التخصيص؟',
      saveSuccess: 'تم حفظ التخصيص بنجاح',
      deleteSuccess: 'تم حذف التخصيص بنجاح',
      partner: 'الشريك',
      product: 'المنتج',
      quantity: 'الكمية المخصصة',
      remaining: 'الكمية المتبقية',
      share: 'نسبة الربح',
      status: 'الحالة',
      active: 'نشط',
      fulfilled: 'مكتمل',
      all: 'الكل',
      noAssignments: 'لا توجد تخصيصات مضافة',
      statsTotal: 'إجمالي التخصيصات',
      statsActive: 'النشطة',
      statsFulfilled: 'المكتملة',
      details: 'تفاصيل التخصيص',
      insufficientStock: 'الكمية غير متوفرة في المخزون',
      alreadyAssigned: 'هذا المنتج مخصص بالفعل',
    }
  },

  reports: {
    noData: 'لا توجد بيانات',
    showing: 'عرض',
    to: 'إلى',
    of: 'من',
    selectDateRange: 'اختر نطاق التاريخ',
    viewDetails: 'عرض التفاصيل',
    id: 'المعرف',
    status: 'الحالة',
    total: 'الإجمالي',
    paymentMethod: 'طريقة الدفع',
    noMoreData: 'لا توجد مزيد من البيانات',
    individualTransactions: 'المعاملات الفردية',
    transactionDetails: 'تفاصيل المعاملة',
    sales: {
      title: 'تقرير المبيعات',
      subtitle: 'تحليلات يومية وتفصيل الإيرادات لكل معاملة',
      totalRevenue: 'إجمالي الإيرادات',
      netProfit: 'صافي الربح',
      salesCount: 'عدد المبيعات',
      avgMargin: 'متوسط هامش الربح',
      date: 'التاريخ',
      dailyStatistics: 'الإحصائيات اليومية',
      count: 'العدد',
      amount: 'المبلغ',
      time: 'الوقت',
    },
    partners: {
      title: 'تقرير الشركاء',
      subtitle: 'توزيعات الأرباح وتفاصيل المستثمرين',
      totalPayout: 'إجمالي التوزيعات',
      partnersCount: 'عدد الشركاء',
      partnerName: 'اسم الشريك',
      amount: 'المبلغ',
      partnerCountSubtitle: 'عبر جميع الشركاء النشطين',
      avgPayout: 'متوسط التوزيع',
    },
    inventory: {
      title: 'تقرير المخزون',
      subtitle: 'حركة المخزون والتنبيهات',
      totalMovements: 'إجمالي الحركات',
      lowStockItems: 'المنتجات المنخفضة',
      movementsByReason: 'الحركات حسب السبب',
      productName: 'اسم المنتج',
      movementType: 'نوع الحركة',
      quantity: 'الكمية',
    },
    export: {
      csv: 'تصدير CSV',
      excel: 'تصدير Excel',
      pdf: 'تصدير PDF',
      exporting: 'جاري التصدير...',
      exportSuccess: 'تم التصدير بنجاح',
      exportFailed: 'فشل التصدير',
    },
  },

  settings: {
    title: 'الإعدادات',
    subtitle: 'تكوين النظام والطرق والرسوم',
    paymentMethods: 'طرق الدفع',
    feePresets: 'إعدادات الرسوم',
    feePresetsDescription: 'تكوين أزرار المبالغ السريعة لكل نوع رسوم. الحد الأقصى 8 إعدادات مسبقة لكل نوع.',
    presetAmounts: 'مبالغ الإعداد المسبق لـ',
    addPreset: 'إضافة إعداد مسبق',
    currentPresets: 'الإعدادات المسبقة الحالية',
    noPresets: 'لم يتم تكوين إعدادات مسبقة',
    vatSettings: 'إعدادات ضريبة القيمة المضافة',
    vatEnabled: 'تفعيل الضريبة',
    vatRate: 'نسبة الضريبة',
    addPaymentMethod: 'إضافة طريقة دفع',
    methodName: 'اسم الطريقة',
    methodNameAr: 'اسم الطريقة (بالعربية)',
    methodNameEn: 'اسم الطريقة (بالإنجليزية)',
    isActive: 'نشط',
    systemSettings: 'إعدادات النظام',
  },


  sales: {
    title: 'المبيعات',
    newSale: 'بيع جديد',
    saleDetails: 'تفاصيل البيع',
    saleId: 'رقم البيع',
    items: 'المنتجات',
    paymentMethod: 'طريقة الدفع',
    subtotal: 'المجموع الفرعي',
    fees: 'الرسوم',
    vat: 'ضريبة القيمة المضافة',
    total: 'الإجمالي',
    profit: 'الربح',
    cost: 'التكلفة',
    date: 'التاريخ',
    customer: 'العميل',
    noSalesFound: 'لم يتم العثور على مبيعات',
  },

  forms: {
    required: 'مطلوب',
    optional: 'اختياري',
    invalidFormat: 'تنسيق غير صالح',
    minLength: 'الحد الأدنى {min} أحرف',
    maxLength: 'الحد الأقصى {max} أحرف',
    minValue: 'القيمة لا تقل عن {min}',
    maxValue: 'القيمة لا تتجاوز {max}',
    invalidEmail: 'البريد الإلكتروني غير صالح',
    invalidNumber: 'الرقم غير صالح',
    invalidDate: 'التاريخ غير صالح',
    passwordMismatch: 'كلمات المرور غير متطابقة',
  },

  errors: {
    networkError: 'خطأ في الاتصال بالشبكة',
    serverError: 'خطأ في الخادم. يرجى المحاولة لاحقاً',
    validationError: 'يرجى التحقق من البيانات المدخلة',
    notFound: 'لم يتم العثور على البيانات',
    permissionDenied: 'ليس لديك صلاحية للقيام بهذا الإجراء',
    unknownError: 'حدث خطأ غير متوقع',
    insufficientStock: 'الكمية المطلوبة غير متوفرة في المخزون',
    duplicateEntry: 'هذا العنصر موجود بالفعل',
    operationFailed: 'فشلت العملية',
    fetchFailed: 'فشل في جلب البيانات',
    saveFailed: 'فشل في حفظ البيانات',
    deleteFailed: 'فشل في حذف البيانات',
    connectionLost: 'انقطع الاتصال',
    connectionRestored: 'تم استعادة الاتصال',
  },

  auth: {
    welcomeBack: 'مرحباً بعودتك',
    loginToAccount: 'سجل الدخول إلى حسابك',
    email: 'البريد الإلكتروني',
    emailAddress: 'عنوان البريد الإلكتروني',
    password: 'كلمة المرور',
    forgotPassword: 'نسيت؟',
    signIn: 'تسجيل الدخول',
    createAccount: 'إنشاء حساب',
    newHere: 'جديد هنا؟',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfService: 'شروط الخدمة',
  },

  emptyStates: {
    noProducts: 'لا توجد منتجات. أضف منتجاً جديداً للبدء.',
    noSales: 'لا توجد مبيعات بعد.',
    noPartners: 'لا يوجد شركاء. أضف شريكاً للبدء.',
    noInventory: 'لا توجد سجلات مخزون.',
    noHistory: 'لا يوجد سجل.',
  },

  status: {
    active: 'نشط',
    inactive: 'غير نشط',
    pending: 'قيد الانتظار',
    completed: 'مكتمل',
    cancelled: 'ملغي',
  },

  dates: {
    today: 'اليوم',
    yesterday: 'أمس',
    thisWeek: 'هذا الأسبوع',
    thisMonth: 'هذا الشهر',
    lastMonth: 'الشهر الماضي',
    thisYear: 'هذا العام',
    custom: 'مخصص',
    from: 'من',
    to: 'إلى',
  },

  numbers: {
    currency: 'ج.س',
    items: 'عناصر',
    page: 'صفحة',
    of: 'من',
    showing: 'عرض',
  },

  chart: {
    revenue: 'الإيرادات',
    profit: 'الربح',
    sales: 'المبيعات',
    restocks: 'إعادة التخزين',
    reversals: 'الإلغاءات',
    date: 'التاريخ',
    value: 'القيمة',
    name: 'الاسم',
    percentage: 'النسبة',
  },
} as const;

export type ArabicConstants = typeof ARABIC;
