"""implement_reversal_model

Revision ID: 374b96547931
Revises: 8e1f63b297a9
Create Date: 2026-04-05 22:50:48.733213

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '374b96547931'
down_revision = '8e1f63b297a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sale_reversals_original_sale_id', table_name='sale_reversals')
    op.drop_table('sale_reversals')
    op.add_column('sales', sa.Column('original_sale_id', sa.UUID(), nullable=True))
    op.add_column('sales', sa.Column('is_reversal', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_sales_original_sale_id'), 'sales', ['original_sale_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'sales', ['original_sale_id'], ['id'])
    
    op.drop_constraint('chk_subtotal_positive', 'sales', type_='check')
    op.drop_constraint('chk_fees_positive', 'sales', type_='check')
    # These might not exist based on \d, but safely keep drop if they do, or use IF EXISTS (alembic doesn't native support if exists for constraints, better to execute raw sql if unsure, or just drop the ones we confirmed).
    op.execute("ALTER TABLE sales DROP CONSTRAINT IF EXISTS check_total_nonnegative")
    op.execute("ALTER TABLE sales DROP CONSTRAINT IF EXISTS check_total_cost_nonnegative")
    op.drop_constraint('chk_quantity_positive', 'sale_items', type_='check')
    op.drop_constraint('chk_line_total_positive', 'sale_items', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_original_sale_id'), table_name='sales')
    op.drop_column('sales', 'is_reversal')
    op.drop_column('sales', 'original_sale_id')
    
    op.create_check_constraint('chk_subtotal_positive', 'sales', 'subtotal >= 0')
    op.create_check_constraint('chk_fees_positive', 'sales', 'fees_total >= 0')
    op.create_check_constraint('chk_quantity_positive', 'sale_items', 'quantity > 0')
    op.create_check_constraint('chk_line_total_positive', 'sale_items', 'line_total >= 0')
    op.create_table('sale_reversals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('original_sale_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reversal_sale_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('branch_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['original_sale_id'], ['sales.id'], name='sale_reversals_original_sale_id_fkey'),
    sa.ForeignKeyConstraint(['reversal_sale_id'], ['sales.id'], name='sale_reversals_reversal_sale_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sale_reversals_pkey')
    )
    op.create_index('ix_sale_reversals_original_sale_id', 'sale_reversals', ['original_sale_id'], unique=False)
    # ### end Alembic commands ###
