"""implement_partners_engine

Revision ID: 378166ead740
Revises: de35f06ee1ad
Create Date: 2026-04-05 23:15:54.561052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '378166ead740'
down_revision = 'de35f06ee1ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_distributions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('payout_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('snapshot_fields', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_distributions_partner_id'), 'partner_distributions', ['partner_id'], unique=False)
    op.create_index(op.f('ix_partner_distributions_project_id'), 'partner_distributions', ['project_id'], unique=False)
    op.add_column('partners', sa.Column('investment_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.add_column('partners', sa.Column('profit_percentage', sa.Numeric(precision=5, scale=2), nullable=False))
    op.drop_column('partners', 'percentage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.drop_column('partners', 'profit_percentage')
    op.drop_column('partners', 'investment_amount')
    op.drop_index(op.f('ix_partner_distributions_project_id'), table_name='partner_distributions')
    op.drop_index(op.f('ix_partner_distributions_partner_id'), table_name='partner_distributions')
    op.drop_table('partner_distributions')
    # ### end Alembic commands ###
