"""add_sale_payments

Revision ID: 66f9164d52fd
Revises: 9533b1dbbe0c
Create Date: 2026-04-15 19:00:48.897692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f9164d52fd'
down_revision = '9533b1dbbe0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_payments',
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('payment_method_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_payments_payment_method_id'), 'sale_payments', ['payment_method_id'], unique=False)
    op.create_index(op.f('ix_sale_payments_sale_id'), 'sale_payments', ['sale_id'], unique=False)

    # Data migration: Populate sale_payments from existing sales
    connection = op.get_bind()
    sales_query = sa.text("SELECT id, payment_method_id, grand_total, created_at FROM sales")
    sales = connection.execute(sales_query).fetchall()

    if sales:
        import uuid
        for sale in sales:
            connection.execute(
                sa.text(
                    "INSERT INTO sale_payments (id, sale_id, payment_method_id, amount, created_at, updated_at) "
                    "VALUES (:id, :sale_id, :payment_method_id, :amount, :created_at, :updated_at)"
                ),
                {
                    "id": str(uuid.uuid4()),
                    "sale_id": str(sale.id),
                    "payment_method_id": str(sale.payment_method_id),
                    "amount": sale.grand_total,
                    "created_at": sale.created_at,
                    "updated_at": sale.created_at,
                }
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_payments_sale_id'), table_name='sale_payments')
    op.drop_index(op.f('ix_sale_payments_payment_method_id'), table_name='sale_payments')
    op.drop_table('sale_payments')
    # ### end Alembic commands ###
