"""financial_snapshots_and_decimal_safety

Revision ID: 8e1f63b297a9
Revises: ff61dc814413
Create Date: 2026-04-05 22:34:34.958460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1f63b297a9'
down_revision = 'ff61dc814413'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_name_key', 'categories', type_='unique')
    op.drop_index('idx_categories_name', table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.drop_index('idx_inventory_log_product', table_name='inventory_log')
    op.drop_index('idx_inventory_log_reference', table_name='inventory_log', postgresql_where='(reference_id IS NOT NULL)')
    op.create_index(op.f('ix_inventory_log_product_id'), 'inventory_log', ['product_id'], unique=False)
    op.drop_constraint('payment_methods_name_key', 'payment_methods', type_='unique')
    op.create_index(op.f('ix_payment_methods_is_active'), 'payment_methods', ['is_active'], unique=False)
    op.create_index(op.f('ix_payment_methods_name'), 'payment_methods', ['name'], unique=True)
    op.drop_index('idx_products_active', table_name='products')
    op.drop_index('idx_products_category', table_name='products')
    op.drop_index('idx_products_name', table_name='products', postgresql_using='gin')
    op.drop_index('idx_products_sku', table_name='products', postgresql_where='(sku IS NOT NULL)')
    op.drop_constraint('products_sku_key', 'products', type_='unique')
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.drop_index('idx_sale_fees_sale', table_name='sale_fees')
    op.create_index(op.f('ix_sale_fees_sale_id'), 'sale_fees', ['sale_id'], unique=False)
    op.drop_constraint('sale_fees_sale_id_fkey', 'sale_fees', type_='foreignkey')
    op.create_foreign_key(None, 'sale_fees', 'sales', ['sale_id'], ['id'])
    op.add_column('sale_items', sa.Column('base_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('sale_items', sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.drop_index('idx_sale_items_sale', table_name='sale_items')
    op.create_index(op.f('ix_sale_items_product_id'), 'sale_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_sale_items_sale_id'), 'sale_items', ['sale_id'], unique=False)
    op.drop_constraint('sale_items_product_id_fkey', 'sale_items', type_='foreignkey')
    op.drop_constraint('sale_items_sale_id_fkey', 'sale_items', type_='foreignkey')
    op.create_foreign_key(None, 'sale_items', 'sales', ['sale_id'], ['id'])
    op.create_foreign_key(None, 'sale_items', 'products', ['product_id'], ['id'])
    op.drop_index('idx_sale_reversals_original', table_name='sale_reversals')
    op.create_index(op.f('ix_sale_reversals_original_sale_id'), 'sale_reversals', ['original_sale_id'], unique=False)
    op.drop_constraint('sale_reversals_reversal_sale_id_fkey', 'sale_reversals', type_='foreignkey')
    op.drop_constraint('sale_reversals_original_sale_id_fkey', 'sale_reversals', type_='foreignkey')
    op.create_foreign_key(None, 'sale_reversals', 'sales', ['original_sale_id'], ['id'])
    op.create_foreign_key(None, 'sale_reversals', 'sales', ['reversal_sale_id'], ['id'])
    
    # Add new columns as nullable first
    op.add_column('sales', sa.Column('vat_total', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('sales', sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('sales', sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('sales', sa.Column('profit', sa.Numeric(precision=12, scale=2), nullable=True))
    
    # Migrate data from old columns
    op.execute("UPDATE sales SET vat_total = vat_amount, grand_total = total, total_cost = 0, profit = total")
    
    # Set to NOT NULL
    op.alter_column('sales', 'grand_total', nullable=False)
    op.alter_column('sales', 'total_cost', nullable=False)
    op.alter_column('sales', 'profit', nullable=False)
    
    op.drop_index('idx_sales_created_at', table_name='sales')
    op.drop_index('idx_sales_payment_method', table_name='sales')
    op.create_index(op.f('ix_sales_payment_method_id'), 'sales', ['payment_method_id'], unique=False)
    op.drop_column('sales', 'total')
    op.drop_column('sales', 'vat_amount')
    op.drop_constraint('settings_key_key', 'settings', type_='unique')
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.create_unique_constraint('settings_key_key', 'settings', ['key'])
    op.add_column('sales', sa.Column('vat_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_sales_payment_method_id'), table_name='sales')
    op.create_index('idx_sales_payment_method', 'sales', ['payment_method_id'], unique=False)
    op.create_index('idx_sales_created_at', 'sales', [sa.text('created_at DESC')], unique=False)
    op.drop_column('sales', 'profit')
    op.drop_column('sales', 'total_cost')
    op.drop_column('sales', 'grand_total')
    op.drop_column('sales', 'vat_total')
    op.drop_constraint(None, 'sale_reversals', type_='foreignkey')
    op.drop_constraint(None, 'sale_reversals', type_='foreignkey')
    op.create_foreign_key('sale_reversals_original_sale_id_fkey', 'sale_reversals', 'sales', ['original_sale_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('sale_reversals_reversal_sale_id_fkey', 'sale_reversals', 'sales', ['reversal_sale_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_sale_reversals_original_sale_id'), table_name='sale_reversals')
    op.create_index('idx_sale_reversals_original', 'sale_reversals', ['original_sale_id'], unique=False)
    op.drop_constraint(None, 'sale_items', type_='foreignkey')
    op.drop_constraint(None, 'sale_items', type_='foreignkey')
    op.create_foreign_key('sale_items_sale_id_fkey', 'sale_items', 'sales', ['sale_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('sale_items_product_id_fkey', 'sale_items', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_sale_items_sale_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_product_id'), table_name='sale_items')
    op.create_index('idx_sale_items_sale', 'sale_items', ['sale_id'], unique=False)
    op.drop_column('sale_items', 'vat_rate')
    op.drop_column('sale_items', 'base_cost')
    op.drop_constraint(None, 'sale_fees', type_='foreignkey')
    op.create_foreign_key('sale_fees_sale_id_fkey', 'sale_fees', 'sales', ['sale_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_sale_fees_sale_id'), table_name='sale_fees')
    op.create_index('idx_sale_fees_sale', 'sale_fees', ['sale_id'], unique=False)
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.create_unique_constraint('products_sku_key', 'products', ['sku'])
    op.create_index('idx_products_sku', 'products', ['sku'], unique=False, postgresql_where='(sku IS NOT NULL)')
    op.create_index('idx_products_name', 'products', ['name'], unique=False, postgresql_using='gin')
    op.create_index('idx_products_category', 'products', ['category_id'], unique=False)
    op.create_index('idx_products_active', 'products', ['is_active'], unique=False)
    op.drop_index(op.f('ix_payment_methods_name'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_is_active'), table_name='payment_methods')
    op.create_unique_constraint('payment_methods_name_key', 'payment_methods', ['name'])
    op.drop_index(op.f('ix_inventory_log_product_id'), table_name='inventory_log')
    op.create_index('idx_inventory_log_reference', 'inventory_log', ['reference_id'], unique=False, postgresql_where='(reference_id IS NOT NULL)')
    op.create_index('idx_inventory_log_product', 'inventory_log', ['product_id', sa.text('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index('idx_categories_name', 'categories', ['name'], unique=False)
    op.create_unique_constraint('categories_name_key', 'categories', ['name'])
    # ### end Alembic commands ###
