"""add_partner_id_to_products

Revision ID: b7c8b4e1ddfa
Revises: 74d2e1f1c3a5
Create Date: 2026-04-11 16:30:29.412079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7c8b4e1ddfa'
down_revision = '74d2e1f1c3a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_inventory_log_created_at'), 'inventory_log', ['created_at'], unique=False)
    op.alter_column('partner_wallet_transactions', 'partner_id',
               existing_type=sa.UUID(),
               comment='Partner whose wallet changed',
               existing_nullable=False)
    op.alter_column('partner_wallet_transactions', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Credit (positive) or debit (negative)',
               existing_nullable=False)
    op.alter_column('partner_wallet_transactions', 'transaction_type',
               existing_type=sa.VARCHAR(length=50),
               comment="'sale_profit' or 'manual_adjustment'",
               existing_nullable=False)
    op.alter_column('partner_wallet_transactions', 'reference_id',
               existing_type=sa.UUID(),
               comment='FK to sale_id or NULL for manual',
               existing_nullable=True)
    op.alter_column('partner_wallet_transactions', 'reference_type',
               existing_type=sa.VARCHAR(length=50),
               comment="'sale' or 'manual'",
               existing_nullable=True)
    op.alter_column('partner_wallet_transactions', 'description',
               existing_type=sa.TEXT(),
               comment='Human-readable description',
               existing_nullable=True)
    op.alter_column('partner_wallet_transactions', 'balance_after',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Wallet balance after this transaction',
               existing_nullable=False)
    op.alter_column('partner_wallet_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Transaction timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_wallet_transactions', 'created_by',
               existing_type=sa.UUID(),
               comment='User who initiated transaction',
               existing_nullable=True)
    op.drop_index('idx_partner_transactions', table_name='partner_wallet_transactions')
    op.create_index('idx_partner_transactions', 'partner_wallet_transactions', ['partner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_partner_wallet_transactions_partner_id'), 'partner_wallet_transactions', ['partner_id'], unique=False)
    op.alter_column('product_assignments', 'partner_id',
               existing_type=sa.UUID(),
               comment='Partner receiving profit share',
               existing_nullable=False)
    op.alter_column('product_assignments', 'product_id',
               existing_type=sa.UUID(),
               comment='Product assigned to partner',
               existing_nullable=False)
    op.alter_column('product_assignments', 'assigned_quantity',
               existing_type=sa.INTEGER(),
               comment='Original quantity assigned',
               existing_nullable=False)
    op.alter_column('product_assignments', 'remaining_quantity',
               existing_type=sa.INTEGER(),
               comment='Quantity remaining unsold',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('product_assignments', 'share_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Profit share (overrides partner default)',
               existing_nullable=False)
    op.alter_column('product_assignments', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment="'active' or 'fulfilled'",
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('product_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_assignments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_assignments', 'fulfilled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When remaining_quantity hit 0',
               existing_nullable=True)
    op.alter_column('product_assignments', 'created_by',
               existing_type=sa.UUID(),
               comment='User who created assignment',
               existing_nullable=True)
    op.alter_column('product_assignments', 'branch_id',
               existing_type=sa.UUID(),
               comment='Branch for multi-branch support',
               existing_nullable=True)
    op.create_index(op.f('ix_product_assignments_partner_id'), 'product_assignments', ['partner_id'], unique=False)
    op.create_index(op.f('ix_product_assignments_product_id'), 'product_assignments', ['product_id'], unique=False)
    op.add_column('products', sa.Column('partner_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_products_partner_id'), 'products', ['partner_id'], unique=False)
    op.create_foreign_key(None, 'products', 'partners', ['partner_id'], ['id'], ondelete='SET NULL')
    op.drop_column('products', 'base_cost')
    op.create_index(op.f('ix_sales_created_at'), 'sales', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_created_at'), table_name='sales')
    op.add_column('products', sa.Column('base_cost', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_partner_id'), table_name='products')
    op.drop_column('products', 'partner_id')
    op.drop_index(op.f('ix_product_assignments_product_id'), table_name='product_assignments')
    op.drop_index(op.f('ix_product_assignments_partner_id'), table_name='product_assignments')
    op.alter_column('product_assignments', 'branch_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Branch for multi-branch support',
               existing_nullable=True)
    op.alter_column('product_assignments', 'created_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User who created assignment',
               existing_nullable=True)
    op.alter_column('product_assignments', 'fulfilled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When remaining_quantity hit 0',
               existing_nullable=True)
    op.alter_column('product_assignments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_assignments', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="'active' or 'fulfilled'",
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('product_assignments', 'share_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Profit share (overrides partner default)',
               existing_nullable=False)
    op.alter_column('product_assignments', 'remaining_quantity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Quantity remaining unsold',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('product_assignments', 'assigned_quantity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Original quantity assigned',
               existing_nullable=False)
    op.alter_column('product_assignments', 'product_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Product assigned to partner',
               existing_nullable=False)
    op.alter_column('product_assignments', 'partner_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Partner receiving profit share',
               existing_nullable=False)
    op.drop_index(op.f('ix_partner_wallet_transactions_partner_id'), table_name='partner_wallet_transactions')
    op.drop_index('idx_partner_transactions', table_name='partner_wallet_transactions')
    op.create_index('idx_partner_transactions', 'partner_wallet_transactions', ['partner_id', sa.text('created_at DESC')], unique=False)
    op.alter_column('partner_wallet_transactions', 'created_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User who initiated transaction',
               existing_nullable=True)
    op.alter_column('partner_wallet_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Transaction timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_wallet_transactions', 'balance_after',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Wallet balance after this transaction',
               existing_nullable=False)
    op.alter_column('partner_wallet_transactions', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Human-readable description',
               existing_nullable=True)
    op.alter_column('partner_wallet_transactions', 'reference_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="'sale' or 'manual'",
               existing_nullable=True)
    op.alter_column('partner_wallet_transactions', 'reference_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to sale_id or NULL for manual',
               existing_nullable=True)
    op.alter_column('partner_wallet_transactions', 'transaction_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="'sale_profit' or 'manual_adjustment'",
               existing_nullable=False)
    op.alter_column('partner_wallet_transactions', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Credit (positive) or debit (negative)',
               existing_nullable=False)
    op.alter_column('partner_wallet_transactions', 'partner_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Partner whose wallet changed',
               existing_nullable=False)
    op.drop_index(op.f('ix_inventory_log_created_at'), table_name='inventory_log')
    # ### end Alembic commands ###
