"""Add idempotency_key to Sale

Revision ID: ff61dc814413
Revises: t010_add_updated_at
Create Date: 2026-04-05 18:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff61dc814413'
down_revision: Union[str, None] = 't010_add_updated_at'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_sales_idempotency_key'), 'sales', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_idempotency_key'), table_name='sales')
    op.drop_column('sales', 'idempotency_key')
    # ### end Alembic commands ###
